### ISSUE TITLE
Markdown content

### ISSUE THREAD

**Issue by LudvigHz** [koseprogg/codesandbox-frontend#15]
Task descriptions should be using markdown.

**Comment by mariussd** [comment]
I very much agree

**Comment by asmundh** [comment]
Markdown på både subtasks og description, kanskje?

**Comment by LudvigHz** [comment]
Ideelt sett kan vi egt bare fjerne subtasks og kun ha description som beskriver oppgaven fullstendig.

**Comment by asmundh** [comment]
Godt poeng!
